=== benwest/psa-schema/schema/a-power-store.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "psa/a-power-store.json",
    "type": "object",
    "properties": {
        "items": {
            "type": "array",
            "items": {
                "$ref": "definitions/product-thumbnail.json"
            }
        },
        "productTypes": {
            "$ref": "definitions/tags.json"
        },
        "tags": {
            "$ref": "definitions/tags.json"
        },
        "info": {
            "$ref": "definitions/pagination.json"
        }
    },
    "required": [
        "items",
        "productTypes",
        "tags",
        "info"
    ],
    "additionalProperties": false
}

=== benwest/psa-schema/examples/a-power-store.json
{
    "items": [
        {
            "title": "On the stream: Catalogue (special edition)",
            "slug": "on-the-stream-catalogue-special-edition",
            "image": {
                "ratio": 0.6666666666666666,
                "placeholder": "http://powerstationofart.com/img/on-the-stream-caalogue.jpg_placeholder.jpg",
                "srcs": [
                    {
                        "width": 200,
                        "height": 133,
                        "url": "http://powerstationofart.com/img/on-the-stream-caalogue.jpg_200.jpg"
                    },
                    {
                        "width": 400,
                        "height": 266,
                        "url": "http://powerstationofart.com/img/on-the-stream-caalogue.jpg_400.jpg"
                    },
                    {
                        "width": 800,
                        "height": 533,
                        "url": "http://powerstationofart.com/img/on-the-stream-caalogue.jpg_800.jpg"
                    },
                    {
                        "width": 1200,
                        "height": 800,
                        "url": "http://powerstationofart.com/img/on-the-stream-caalogue.jpg_1200.jpg"
                    },
                    {
                        "width": 1600,
                        "height": 1066,
                        "url": "http://powerstationofart.com/img/on-the-stream-caalogue.jpg_1600.jpg"
                    }
                ]
            },
            "productType": {
                "title": "Publication",
                "slug": "publication"
            },
            "price": 258
        }
    ],
    "productTypes": [
        {
            "title": "Publication",
            "slug": "Publication"
        },
        {
            "title": "Postcard",
            "slug": "postcard"
        },
        {
            "title": "Poster",
            "slug": "poster"
        }
    ],
    "tags": [
        {
            "title": "On the Stream",
            "slug": "on-the-stream"
        },
        {
            "title": "Visible X Invisible",
            "slug": "visible-x-invisible"
        },
        {
            "title": "Yu Youhan",
            "slug": "yu-youhan"
        }
    ],
    "info": {
        "count": 48
    }
}
