=== benwest/psa-schema/schema/news-item.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "psa/news-item.json",
    "description": "News post in What's On",
    "type": "object",
    "properties": {
        "slug": {
            "$ref": "definitions/slug.json"
        },
        "title": {
            "type": "string"
        },
        "newsType": {
            "$ref": "definitions/tag.json"
        },
        "tags": {
            "$ref": "definitions/tags.json"
        },
        "date": {
            "type": "string",
            "format": "date-time"
        },
        "blocks": {
            "$ref": "definitions/blocks.json"
        }
    },
    "required": [
        "slug",
        "title",
        "newsType",
        "tags",
        "date",
        "blocks"
    ]
}

=== benwest/psa-schema/examples/whats-on/news/emerging-curators-project-2019.json
{
    "title": "Emerging Curators Project 2019",
    "slug": "emerging-curators-project-2019",
    "newsType": {
        "title": "Announcement",
        "slug": "announcement"
    },
    "tags": [],
    "date": "2018-11-13T20:20:39+00:00",
    "blocks": [
        {
            "type": "text",
            "body": "The Emerging Curators Project, hosted by the Power Station of Art, was first launched in 2014, and has so far helped more than 20 young Chinese curators realize 14 exhibitions. Their practices at the power-plant-converted art space have not only expanded our curatorial horizons, but also allowed more young Chinese artists and their talents to be accessed and appreciated by both the audience and the international art community"
        }
    ]
}
