=== benwest/psa-schema/schema/program.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "psa/program.json",
    "description": "Index for a Program",
    "type": "object",
    "properties": {
        "slug": {
            "$ref": "definitions/slug.json"
        },
        "title": {
            "type": "string"
        },
        "colors": {
            "$ref": "definitions/color-scheme.json"
        },
        "pages": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string"
                    },
                    "slug": {
                        "$ref": "definitions/slug.json"
                    }
                },
                "additionalProperties": false,
                "required": [
                    "title",
                    "slug"
                ]
            }
        }
    },
    "required": [
        "slug",
        "title",
        "pages"
    ],
    "additionalProperties": false
}

=== benwest/psa-schema/examples/whats-on/programs/shanghai-bienniale.json
{
    "title": "Shanghai Bienniale",
    "slug": "shanghai-bienialle",
    "colors": {
        "background": "#14E42E",
        "text": "#000000"
    },
    "pages": [
        {
            "title": "Theme",
            "slug": "theme"
        },
        {
            "title": "Artists & Work",
            "slug": "artists-and-work"
        },
        {
            "title": "Events",
            "slug": "events"
        },
        {
            "title": "News",
            "slug": "news"
        }
    ]
}
