=== benwest/psa-schema/schema/psa-collections.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "psa/psa-collections.json",
    "type": "object",
    "properties": {
        "items": {
            "type": "array",
            "items": {
                "$ref": "definitions/artwork-thumbnail.json"
            }
        },
        "artworkTypes": {
            "$ref": "definitions/tags.json"
        },
        "tags": {
            "$ref": "definitions/tags.json"
        },
        "info": {
            "$ref": "definitions/pagination.json"
        }
    },
    "required": [
        "items",
        "artworkTypes",
        "tags",
        "info"
    ],
    "additionalProperties": false
}

=== benwest/psa-schema/examples/psa-collections.json
{
    "items": [
        {
            "slug": "new-new-angel",
            "title": "New New Angel",
            "artist": "Boat Zhang",
            "date": "2013/2016",
            "artworkType": {
                "title": "Video",
                "slug": "video"
            },
            "image": {
                "ratio": 0.6666666666666666,
                "placeholder": "http://powerstationofart.com/img/new-new-angel-1_placeholder.jpg",
                "srcs": [
                    {
                        "width": 200,
                        "height": 133,
                        "url": "http://powerstationofart.com/img/new-new-angel-1_200.jpg"
                    },
                    {
                        "width": 400,
                        "height": 266,
                        "url": "http://powerstationofart.com/img/new-new-angel-1_400.jpg"
                    },
                    {
                        "width": 800,
                        "height": 533,
                        "url": "http://powerstationofart.com/img/new-new-angel-1_800.jpg"
                    },
                    {
                        "width": 1200,
                        "height": 800,
                        "url": "http://powerstationofart.com/img/new-new-angel-1_1200.jpg"
                    },
                    {
                        "width": 1600,
                        "height": 1066,
                        "url": "http://powerstationofart.com/img/new-new-angel-1_1600.jpg"
                    }
                ]
            }
        },
        {
            "slug": "new-new-angel",
            "title": "New New Angel",
            "artist": "Boat Zhang",
            "date": "2013/2016",
            "artworkType": {
                "title": "Video",
                "slug": "video"
            },
            "image": {
                "ratio": 0.6666666666666666,
                "placeholder": "http://powerstationofart.com/img/new-new-angel-1_placeholder.jpg",
                "srcs": [
                    {
                        "width": 200,
                        "height": 133,
                        "url": "http://powerstationofart.com/img/new-new-angel-1_200.jpg"
                    },
                    {
                        "width": 400,
                        "height": 266,
                        "url": "http://powerstationofart.com/img/new-new-angel-1_400.jpg"
                    },
                    {
                        "width": 800,
                        "height": 533,
                        "url": "http://powerstationofart.com/img/new-new-angel-1_800.jpg"
                    },
                    {
                        "width": 1200,
                        "height": 800,
                        "url": "http://powerstationofart.com/img/new-new-angel-1_1200.jpg"
                    },
                    {
                        "width": 1600,
                        "height": 1066,
                        "url": "http://powerstationofart.com/img/new-new-angel-1_1600.jpg"
                    }
                ]
            }
        }
    ],
    "artworkTypes": [
        {
            "title": "Video",
            "slug": "video"
        },
        {
            "title": "Performance",
            "slug": "performance"
        },
        {
            "title": "Painting",
            "slug": "painting"
        }
    ],
    "tags": [],
    "info": {
        "count": 312
    }
}
