=== benwest/psa-schema/schema/whats-on.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "psa/whats-on.json",
    "description": "What's On index",
    "type": "object",
    "properties": {
        "activityTypes": {
            "$ref": "definitions/tags.json"
        },
        "newsTypes": {
            "$ref": "definitions/tags.json"
        },
        "tags": {
            "$ref": "definitions/tags.json"
        },
        "programs": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string"
                    },
                    "slug": {
                        "$ref": "definitions/slug.json"
                    }
                },
                "required": [
                    "title",
                    "slug"
                ]
            }
        },
        "membership": {
            "$ref": "definitions/link.json"
        },
        "announcement": {
            "$ref": "definitions/news-thumbnail.json"
        }
    },
    "required": [
        "activityTypes",
        "newsTypes",
        "tags",
        "programs",
        "membership"
    ]
}

=== benwest/psa-schema/examples/whats-on.json
{
    "activityTypes": [
        {
            "title": "Talk",
            "slug": "talk"
        },
        {
            "title": "Workshop",
            "slug": "workshop"
        }
    ],
    "newsTypes": [
        {
            "title": "News",
            "slug": "news"
        },
        {
            "title": "Announcement",
            "slug": "announcement"
        }
    ],
    "tags": [
        {
            "title": "Architecture",
            "slug": "architecture"
        },
        {
            "title": "Design",
            "slug": "design"
        },
        {
            "title": "Photography",
            "slug": "photography"
        },
        {
            "title": "Visual Arts",
            "slug": "visual-arts"
        }
    ],
    "programs": [
        {
            "title": "Architecture Series",
            "slug": "architexture-series"
        },
        {
            "title": "power station of DESIGN",
            "slug": "power-station-of-design"
        },
        {
            "title": "Shanghai Biennialle",
            "slug": "shanghai-biennale"
        }
    ],
    "membership": {
        "label": "Become a Member",
        "url": "http://powerstationofart.com/membership"
    },
    "announcement": {
        "type": "news",
        "title": "PSA 5F Deck Temporarily Closed",
        "slug": "psa-5f-deck-temporarily-closed",
        "newsType": {
            "title": "Notice",
            "slug": "notice"
        },
        "date": "2018-11-13T20:20:39+00:00"
    }
}
